; Values used by native A selector $14 title-list code.
DEF FIRST_FLASH_GAME_INDEX EQU $10
DEF GAME_LIST_END EQU $FF
DEF MINIGAME_MAX_BLOCKS_PLUS_ONE EQU $11
DEF MINIGAME_TITLE_COPY_LIMIT EQU $18
DEF MINIGAME_BLOCK_COUNT EQU $6005
DEF MINIGAME_TITLE EQU $600F
DEF MINIGAME_VALID_MARKER EQU $6044
